### PR TITLE
The mistakes are fixed

### PR DESCRIPTION
**Pull request by Dboi6339-Soupe**
Okay, when it comes to fixing my errors (in the forked wiki repo), I worked out almost all the chinks, I just am trying to figure out 1.) how to test it and 2.) how to resize img assets.

### CODE REVIEW

**Comment by Kekmw** [comment]
Testing it should be in the README file. It shows you how to test this.

**Comment by Dboi6339-Soupe** [comment]
Okay, thank you.

**Comment by Kekmw** [comment]
Service? Can you explain what do you mean by that?
The README should have everything you need.
You can use cmd or powershell for it. Just search in google how to open any of the 2

**Comment by Dboi6339-Soupe** [comment]
I meant like Repl.it, Scrimba, etc.  But okay, just use a cmd or powershell, got it.

**Comment by Kekmw** [comment]
I don't recommend using a service- 
But may i know have you updated it and checked if its working?

**Comment by Kekmw** [comment]
The wind flows through the air as the conversation grows dead.

**Comment by Dboi6339-Soupe** [comment]
Sorry I don't respond frequently, I am also doing school along with my programming career.  I am 14 and all.  I am currently checking and updating.

**Comment by Kekmw** [comment]
No worries. I also have school. And if you saw my staff-intro you'll know how old i am.

**Comment by Dboi6339-Soupe** [comment]
Alright, I don't have the proper equipment yet to fix any issues further, so now it's up to you guys to decide if you want to keep the arrow and fix it further to your liking, or to close this pull request.  I am fine either way.  Love the game, and hope you guys sot out anything ... *cough* currently happening.

**Comment by Kekmw** [comment]
Lol

Closing pull request.

**Pull request closed without merging**
