### PR TITLE
added a scroll-down arrow and updated coverpage.md

### PR DESCRIPTION
**Pull request by Dboi6339-Soupe**
When first logging on the wiki it was very confusing to tell if I should scroll down because I thought the page was still loading.  A lot of friends had told me the same thing, so to prevent confusion, I am making a pull request to add this scroll-down arrow to tell players to scroll down to see the content.  I then called for that image in `coverpage.md` to be at the bottom of the screen.

Let me know if you want me to fix this or this was not a good idea.

### CODE REVIEW

**Comment by Kekmw** [comment]
May i ask why is there like 690k lines added.
And may i ask is this working on your computer?
And can you show me how it looks?

**Review by DamienVesper — COMMENTED** [review]
Includes .replit, node_modules, along with other garbage. Please make sure that you do not include this when committing (pull for latest update to gitignore).

**Comment by BR88C** [comment]
Changes look good, just make sure to add those directories to .gitignore like Damien said. If you need help doing so, feel free to DM me and I can walk you through the process

**Comment by Kekmw** [comment]
I would like to say that. When i tested it. It didn't show what it was intended to show which was the scroll down arrow.

**Comment by Dboi6339-Soupe** [comment]
1. **_Why am I always late to see the conversations?_**
2. In the `ReadMe`, I tried following the directions, but then I saw that it was already done, so tried to revert it to original, guess it didn't work out well, I think that's 1 reason there's a truckload of code.
3. I'm working on just working with Github when changing code in the forked repository, as Repl.it 1.) was recommended to me and 2.) duplicates code when overwriting and adds a whole bunch of other unwanted stuff in the mix when I make a mistake.
Sorry 'bout that, I'm trying my best and working on correcting my mistakes.  Talk to ye then.

**Comment by BR88C** [comment]
> 1. **_Why am I always late to see the conversations?_**
> 2. In the `ReadMe`, I tried following the directions, but then I saw that it was already done, so tried to revert it to original, guess it didn't work out well, I think that's 1 reason there's a truckload of code.
> 3. I'm working on just working with Github when changing code in the forked repository, as Repl.it 1.) was recommended to me and 2.) duplicates code when overwriting and adds a whole bunch of other unwanted stuff in the mix when I make a mistake.
>    Sorry 'bout that, I'm trying my best and working on correcting my mistakes.  Talk to ye then.

2 - What was already done? What were you trying to revert?
3 - Repl.it should not be used, the README tells you how to test the site using docsify's cli module. The README also shows how to install it globally so that you can run it via powershell or cmd

**Pull request closed without merging**
